 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  medicat: # name of the dataset builder
    # dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
            # TODO make this order insensitive
            - /home/users1/linchi/2024WS-FM/PeFoMed/eepy/datasets/medicat/sample.jsonl
          storage: /home/users1/linchi/2024WS-FM/PeFoMed/eepy/datasets/medicat/sample.jsonl
      images:
          storage: /home/users1/linchi/2024WS-FM/PeFoMed/eepy/datasets/medicat/figures

